// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBomOsIEJV5ziLUOobafF1dluOCuGM9muI',
    appId: '1:403888909082:web:e14f531c86be17fac85aa3',
    messagingSenderId: '403888909082',
    projectId: 'artfolio-34460',
    authDomain: 'artfolio-34460.firebaseapp.com',
    storageBucket: 'artfolio-34460.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6PSbssrVdSMdseRCIa32dCIsu1VkBOg',
    appId: '1:403888909082:android:fecac1f68dcac971c85aa3',
    messagingSenderId: '403888909082',
    projectId: 'artfolio-34460',
    storageBucket: 'artfolio-34460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDMm_AiUYgkvyrlRu7Rm5F69-Q6fGK0cg',
    appId: '1:403888909082:ios:ba9e1edcf77e85d0c85aa3',
    messagingSenderId: '403888909082',
    projectId: 'artfolio-34460',
    storageBucket: 'artfolio-34460.appspot.com',
    iosBundleId: 'com.example.artfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDMm_AiUYgkvyrlRu7Rm5F69-Q6fGK0cg',
    appId: '1:403888909082:ios:ba9e1edcf77e85d0c85aa3',
    messagingSenderId: '403888909082',
    projectId: 'artfolio-34460',
    storageBucket: 'artfolio-34460.appspot.com',
    iosBundleId: 'com.example.artfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBomOsIEJV5ziLUOobafF1dluOCuGM9muI',
    appId: '1:403888909082:web:293a8029ed2976afc85aa3',
    messagingSenderId: '403888909082',
    projectId: 'artfolio-34460',
    authDomain: 'artfolio-34460.firebaseapp.com',
    storageBucket: 'artfolio-34460.appspot.com',
  );

}